### ISSUE TITLE
A question about one-bit quantization implementation in tensorflow backend.

### ISSUE THREAD

**Issue by shuo-ouyang** [sands-lab/grace#12]
IMHO, the return type of function `tf.math.less` is `tf.bool`, which is representated by 8 bit. Hence, the code at 
[grace_dl/tensorflow/compressor/onebit.py#L21](https://github.com/sands-lab/grace/blob/b10584bc5296e77e7e9211c5c5a60f374143369c/grace_dl/tensorflow/compressor/onebit.py#L21) is not really one-bit quantization but eight-bit quantization?

**Comment by hangxu0304** [comment]
No. We haven't found a way to do efficient encoding and decoding for low-bits quantization methods. We tried to do it by native Pytorch/Tensorflow API, however, the real throughput will actually be worse due to the computation overhead. If you really care about how much data it transfers, you may refer to our inefficient implementation [here](https://github.com/sands-lab/grace/blob/master/grace_dl/tensorflow/compressor/packing.py).
