### ISSUE TITLE
Example of `pack`, `unpack`

### ISSUE THREAD

**Issue by thadikari** [sands-lab/grace#3]
Hi,
A very useful package and a reference implementation!
I quote from the paper at https://repository.kaust.edu.sa/bitstream/handle/10754/662495/gradient-compression-survey.pdf?sequence=1&isAllowed=y 
> ... `pack` can further compress the representation by encoding several values originally stored in 32-bit into a single 32-bit value. For instance, a 1-bit quantization can pack 32 values into a single 32-bit integer

However I couldn't find any example of `pack` `unpack`. Can you point me to one if there exists one? If not can you add such functionality to for example `SignSGDCompressor`?

**Comment by mcanini** [comment]
Hi. We've currently excluded this functionality from this code release because we could not create an efficient implementation purely based on the TF API. These bit-level manipulations are somewhat method-specific and in general require custom C++ operators to be created. As such, we are still investigating how to best support this functionality.

**Comment by thadikari** [comment]
Oh I see, look forward to seeing that functionality!
